### ISSUE TITLE
New Fw maybe Bug 0.1.2

### ISSUE THREAD

**Issue by Hackrfan** [F5OEO/tezuka_fw#92]
I have just tested the new Fw 0.1.2 on QO 100 and noticed that the TX signal looks terrible here.
See pictures , for comparison Fw 0.37 dirty 
Can anyone confirm this?

![Image](https://github.com/user-attachments/assets/cc0931ad-cd4f-4e5b-a227-476e70636762)
![Image](https://github.com/user-attachments/assets/eb33d0bc-259c-4a9a-b4cb-aa5e4094e502)

**Comment by DG9BFC** [comment]
works totally fine here
dg9bfc sigi

![Image](https://github.com/user-attachments/assets/a2555f08-e73b-4c22-a55d-7f31a87b5038)

**Comment by Hackrfan** [comment]
Here is another picture with version 0.1.1 all settings on the SDR console unchanged.

![Image](https://github.com/user-attachments/assets/0ddaa329-7ba5-4bac-829a-839ffeec7149)

**Comment by raimund56** [comment]
/can confirm.  Raimund in3her

![Image](https://github.com/user-attachments/assets/826b04d1-f287-49c0-8375-a8fde5b7cb47)

**Comment by F5OEO** [comment]
Should be fixed with 148a6e0091c75891c7d5554098440eb73c214e48

**Comment by Hackrfan** [comment]
Sorry, is the fix already integrated in 0.1.2? Or how can I test if it works?
Greetings Georg

**Comment by F5OEO** [comment]
Fix is integrated with 0.1.3. Please confirm.

**Comment by Hackrfan** [comment]
The signal with 0.1.3 is much better but still not clean. sorry but it is.
Compare 0.1.1 with 0.1.3 see screen shot

![Image](https://github.com/user-attachments/assets/c04a18df-6b17-4966-8030-ed838a04bb81)

**Comment by F5OEO** [comment]
Can you check that your TX has same issue using websdr ?

**Comment by DG9BFC** [comment]
on a fresh install of sdrconsole the tune tone is set to "pulses" .. switch it to constant tone and signal should be clean
what you see is the "keyclicks" from these pulses

![Image](https://github.com/user-attachments/assets/bbe5eb67-34bc-4487-8049-674a0b1bcc37)

pulses

![Image](https://github.com/user-attachments/assets/152506c7-f053-4bca-b85e-7787f15f78ad)

settings window for tune tone

![Image](https://github.com/user-attachments/assets/df2a3bf5-b44e-408c-b792-4ee9044cc7b8)

constant tune tone

**Comment by DG9BFC** [comment]
other possible fault .. you may have short interruptions (depending on your soundcard settings, buffer settings etc etc)
there can be a dozen faults that may cause a wide and unclean signal 
and i guess fw is not a reason for it cause in sdrconsole the pluto is used in "pass mode" .. means the fw does "nothing" on the signal

**Comment by Hackrfan** [comment]
Hello Sigi,
I don't know if I didn't express myself clearly enough, I did the different FW states with one and the same console setting and just came to this behavior shown in the pictures.
I also never claimed that the FW 0.32 you are using has this error. The behavior only occurred from FW version 01.2 with F5OEO. Everything was fine before that. So this is definitely not due to my settings but to the FW. Other amateurs can also understand this.
vy 73 Georg

Translated with DeepL.com (free version)

**Comment by F5OEO** [comment]
Closed as inactivity
